# Generated by Django 2.1.5 on 2021-08-13 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(default='This is a <django.db.models.fields.CharField>', max_length=500),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.CharField(default=models.CharField(max_length=150), max_length=2083),
        ),
    ]
