# Generated by Django 2.1.5 on 2021-08-13 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20210813_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(default='This is a product', max_length=400),
        ),
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.CharField(default='This is an image', max_length=2083),
        ),
    ]
